<img align="right" width="200" height="200" src="ovalmoney-logo-green.png">
# A very hurried course in Python
#### By Stefano Calderan, Data Scientist @ Oval Money

## NumPy

In [2]:
import numpy as np        # Standard abbreviation for numpy

### Why NumPy?

- It's free
- It is a package that provides **_high-performance_ vector, matrix and higher-dimensional data structures** (as tensors). *High performance means that computations are VERY fast, because it is  implemented in C and Fortran and calculations are vectorized, i.e. they're formulated with vectors and matrices
- Everybody uses it

### NumPy arrays

The arrays are the basic data structures of `numpy`. Every array supports by default a series of main **mathematical and statistical operations implemented as methods**.  
Let's see how to build them.  

#### NumPy arrays from sequences
We can build them by starting from sequences (lists, sets or tuples)

In [5]:
# 1-Dimensional arrays

a1 = np.array([1, 2, 3])
print(a1.shape)            # .shape is an attribute of every array

(3,)


In [10]:
# a1 is neither a column or a row vector. TO transfrorm it into a column or row vector, you
# have to use the .reshape() method

a_column = a1.reshape(3, 1)           # reshape return a new vector
print('column:\n', a_column)
a_row = a1.reshape(1, 3)
print('row:', a_row)

column:
 [[1]
 [2]
 [3]]
row: [[1 2 3]]


In [18]:
# 2-Dimensional arrays (Matrixes)

M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(M1)
print(M1.shape)
print(M1.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [20]:
# We can specify the type of data inside the array

M2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)   # use the dtype argument to specify the type
print(M2, M2.dtype)                                             # dtype is also an attribute

# if we try to assing a diffent type to an array, we get an error
a1[0] = 'pippo'

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


ValueError: invalid literal for int() with base 10: 'pippo'

#### NumPy arrays from generating functions
Here we see some useful functions provided by `numpy`

In [21]:
# range array
a = np.arange(2, 20, 3)  # start, stop, step
a

array([ 2,  5,  8, 11, 14, 17])

In [23]:
# linspace and logspace arrays
# they divide linearly or in a log-fashion the space contained between start and stop

lin = np.linspace(0, 20, 10)  # start, stop, number of instances
print(lin)

log = np.logspace(0, 2, 5, base=10)
print(log)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [29]:
# zeros and ones

z_vector = np.zeros(5)
z_matrix = np.zeros((3, 3))
z_matrix_from_vector = np.zeros(6).reshape(2, 3)

ones = np.ones((2, 2))

print(z_vector, '\n')
print(z_matrix, '\n')
print(z_matrix_from_vector, '\n')
print(ones)

[0. 0. 0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1.]
 [1. 1.]]


In [30]:
# Diagonal matrixes

iden_matrix = np.identity(5)
diag_matrix = np.diag([1, 2, 3, 4])
diag_offset = np.diag([1, 2, 3], k=1)     # k indicates the offset from the main diagonal

print(iden_matrix, '\n')
print(diag_matrix, '\n')
print(diag_offset, '\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]] 



## Indexing and slicing
`numpy` arrays support basic indexing and slicing, plus new fancy ways of doing it

In [35]:
# 1-dimensional arrays

a = np.arange(0, 3, 0.5)

print(a, '\n')
print(a[3], '\n')
print(a[1:3], '\n')
print(a[::2])

[0.  0.5 1.  1.5 2.  2.5] 

1.5 

[0.5 1. ] 

[0. 1. 2.]


In [38]:
# 2-dimensional arrays

M = np.arange(0, 9).reshape(3, 3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


For multidimensional arrays, the indexing is double: the first index refer to the **row** (first dimension, or axis 0), while the second refers to the **column** (second dimension, or axis 1) 

In [39]:
print( M[0, 1], '\n')
print( M[1, :], '\n')     # all the second row
print( M[:, 2], '\n')     # all the third column
print( M[:2, 1], '\n')    # thirst 2 rows, second column

1 

[3 4 5] 

[2 5 8] 

[1 4] 



In [40]:
# TO DO: starting from the M matrix defined above, create the matrix subM that corresponds to the square submatrix
# in the left bottom corner (with elements 3,4,6,7). Use slicing
# YOUR CODE HERE




### Fancy indexing
`numpy` arrays support very flexible way of indexing.

In [44]:
# select indexes in the order you wish!
my_indexes = [2, 1, -1, -2]

a1 = np.arange(1, 6)
print(a1, '\n')
print( a1[my_indexes])

[1 2 3 4 5] 

[3 2 5 4]


In [55]:
# you can do it also with multidimensional arrays

M = np.arange(0, 16).reshape(4, 4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
M[[1, 2], [0, 3]]

array([ 4, 11])

In [57]:
M[1:3, [0, 2]]     # take all the lines from 1 to 2, only columns 0 and 2

array([[ 4,  6],
       [ 8, 10]])

In [59]:
# BOOLEAN INDEXING!
# 1-dimensional

a = np.arange(9)
a[a < 5]                     # take elemnts from a only where the condition applies

array([0, 1, 2, 3, 4])

In [61]:
a[(a < 5) | (a%2 == 0)]      # | is the bitwise or

array([0, 1, 2, 3, 4, 6, 8])

In [74]:
M = np.arange(16).reshape(4, 4)

M[M < 10]                          # on multidimensional arrays, boolean indexing returns a 1-dimensional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# If you need the INDEXES where the condition applies, and not the elements, use the np.where function

a = np.linspace(10, 50, 5)
print(a)
np.where(a%20 == 0)

[10. 20. 30. 40. 50.]


(array([1, 3]),)

### Array operations
`numpy` arrays allow a vectorization of operations, meaning that under the hood it applies the operation *at the same time* to the whole array

In [83]:
# We'll use these two arrays for all operations demonstrations

v = np.arange(10, 60, 10)
M = np.array( [ [i * 10 + j for j  in range(5)] for i in range(1, 6)])

print(v, v.shape)
print(M, M.shape)

[10 20 30 40 50] (5,)
[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]] (5, 5)


In [84]:
# Scalar operations: the operation is applied to each element

print(v + 1, '\n')
print(v * 5, '\n')
print(M + 10, '\n')
print(M * 10)

[11 21 31 41 51] 

[ 50 100 150 200 250] 

[[20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]] 

[[100 110 120 130 140]
 [200 210 220 230 240]
 [300 310 320 330 340]
 [400 410 420 430 440]
 [500 510 520 530 540]]


**ELEMENT-WISE ARRAY OPERATIONS**  
The operation is applied element by element

In [88]:
# 1-dim array

v2 = np.ones(5)
print(v)
print(v + v2)

v3 = np.arange(5)
print(v * v3)

[10 20 30 40 50]
[11. 21. 31. 41. 51.]
[  0  20  60 120 200]


In [89]:
# multi-dim array

N = np.arange(25).reshape(5, 5)
print(M)
print(N)
print(M * N)

[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[   0   11   24   39   56]
 [ 100  126  154  184  216]
 [ 300  341  384  429  476]
 [ 600  656  714  774  836]
 [1000 1071 1144 1219 1296]]


If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [90]:
M * v

array([[ 100,  220,  360,  520,  700],
       [ 200,  420,  660,  920, 1200],
       [ 300,  620,  960, 1320, 1700],
       [ 400,  820, 1260, 1720, 2200],
       [ 500, 1020, 1560, 2120, 2700]])

All the operations above are the result of the application of **broadcasting**, an operation that automatically *adjusts* the computation between objects having not the same dimension (tough they must have compatible shapes)
<img align="centre" width="450" height="500" src="broadcast.png">


## Linear algebra
Let's now see how to do the basic operations from linear algebra

In [96]:
# INNER PRODUCT
# Use the function np.dot() or the array method .dot

v1 = np.arange(6)
v2 = np.ones(6)

print(v1, v2)
print(np.dot(v1, v2))
print(v1.dot(v2))

[0 1 2 3 4 5] [1. 1. 1. 1. 1. 1.]
15.0
15.0


In [104]:
# MATRIX PRODUCT (m, n) x (n, p)
# Use np.matmul

M = np.arange(6).reshape(2, 3)
N = np.arange(6, 18).reshape(3, 4)
P = np.matmul(M, N)

print(M.shape, N.shape)
print(P, '\n', P.shape)

(2, 3) (3, 4)
[[ 38  41  44  47]
 [128 140 152 164]] 
 (2, 4)


The inner product and the matrix multiplication can be done easily if, instead of creating numpy arrays, we create directly numpy matrixes:

In [105]:
# Matrix product

M = np.mat(np.arange(6).reshape(2, 3))
N = np.mat(np.arange(6, 18).reshape(3, 4))
P = M * N
print(P)

[[ 38  41  44  47]
 [128 140 152 164]]


In [108]:
# Inner product

v1 = np.mat(np.arange(6))              # this is by default a row vector
v2 = np.mat(np.ones(6)).reshape(6, 1)  # we transformed v2 into a column vector
print(v1 * v2)

[[15.]]


#### Other important matrix operations

In [134]:
# Diagonal
S = np.mat([[6, 9, 34], [-5, 6, 7], [33, 10, -9]])
S, S.diagonal()

(matrix([[ 6,  9, 34],
         [-5,  6,  7],
         [33, 10, -9]]), matrix([[ 6,  6, -9]]))

In [135]:
# Transpose
S.T

matrix([[ 6, -5, 33],
        [ 9,  6, 10],
        [34,  7, -9]])

In [136]:
# Determinant
np.linalg.det(S)

-7501.999999999996

In [144]:
# Trace
S.trace()

matrix([[3]])

In [143]:
# Inverse
S.I

matrix([[3]])

In [138]:
S.I * S

matrix([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
        [ 6.59194921e-17,  1.00000000e+00, -1.66533454e-16],
        [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [141]:
# Eigenvalues and eigenvectors

eigen_values, eigen_vecs = np.linalg.eig(S)
eigen_values, eigen_vecs 

(array([-36.28864061,  33.02968399,   6.25895662]),
 matrix([[ 0.58791479,  0.78466076, -0.38123903],
         [ 0.19928542,  0.01534771,  0.89297386],
         [-0.78399077,  0.61973538, -0.23927909]]))

In [142]:
# TO DO: write a function multmat that accepts two numpy arrays a1 and a2 and check if they have compatible
# shapes to perform matrix multiplication. If true, it returns the resulting matrix; else, it slices the
# correct matrix in order to perform the multiplication
# YOUR CODE HERE

def multmat(a1, a2):
    

matrix([[-19.65925846, -24.08844527,  41.83165311]])

### Array data processing
Every numpy array comes equipped with very nice data processing operations

In [152]:
ages = np.array([37, 34, 27, 39, 43, 34, 33, 26, 31, 26, 28, 42, 33, 32, 39, 33])

In [153]:
ages.sum()

537

In [154]:
ages.cumsum()  # cumulative sum

array([ 37,  71,  98, 137, 180, 214, 247, 273, 304, 330, 358, 400, 433,
       465, 504, 537])

In [155]:
ages.prod()   # product

5218580222841458688

In [156]:
ages.cumprod()  # cumulative product

array([                  37,                 1258,                33966,
                    1324674,             56960982,           1936673388,
                63910221804,        1661665766904,       51511638774024,
           1339302608124624,    37500473027489472,  1575019867154557824,
       -3364576605028246656,  3014013081353416704,  6866045730525941760,
        5218580222841458688])

In [159]:
ages2 = ages.copy()
ages2.sort()         # sorting in-place
ages2

array([26, 26, 27, 28, 31, 32, 33, 33, 33, 34, 34, 37, 39, 39, 42, 43])

In [160]:
ages.mean()

33.5625

In [162]:
np.median(ages)  # arrays have no median method

33.0

In [164]:
ages.max(), ages.argmax()    # argmax gives the index of the maximum number

(43, 4)

In [165]:
ages.min(), ages.argmin()

(26, 7)

In [166]:
ages.std()

5.183733572435991

## NumPY Random
This is a very useful library to sample numbers from random distributions